version: "3.8"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:18-bookworm
    container_name: forum-api_devcontainer
    volumes:
      - .:/workspace:cached
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.ssh:/home/node/.ssh
    command: "sleep infinity"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: forum-api_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PGDATABASE} -U ${PGUSER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    driver: local
